// ClipForge AI - Initial Mock Data & Workspace State

import { BrandKit, Clip, LiveSession, Project, Workspace } from '@/types';

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws-forge-1',
  name: 'Nexus Media Labs',
  slug: 'nexus-media',
  creditsTotal: 300,
  creditsUsed: 112,
  plan: 'CREATOR',
  membersCount: 4,
};

export const INITIAL_BRAND_KIT: BrandKit = {
  id: 'bk-1',
  workspaceId: 'ws-forge-1',
  name: 'Nexus Tech Branding',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
  primaryColor: '#8B5CF6',
  secondaryColor: '#22D3EE',
  textColor: '#FFFFFF',
  backgroundColor: '#09090B',
  fontFamily: 'Inter',
  watermarkPos: 'top-right',
  defaultCtaText: '🔥 Subscribe for Daily Tech Insights',
  captionPreset: 'BOLD_CREATOR',
};

export const SAMPLE_CLIPS: Clip[] = [
  {
    id: 'clip-101',
    projectId: 'proj-1',
    title: 'The #1 Mistake Killing 90% of Early Startups',
    hookStatement: 'The biggest mistake early founders make is building for months in isolation.',
    startSec: 0.0,
    endSec: 16.5,
    durationSec: 16.5,
    aspectRatio: '9:16',
    highlightScore: 94,
    sourceScore: 84,
    editQualityScore: 94,
    qaReport: {
      technicalScore: 100,
      hookStrength3s: 98,
      visualPacingScore: 94,
      captionQualityScore: 95,
      audioClarityScore: 96,
      reframingScore: 92,
      deadSpaceRemovalScore: 98,
      overallQualityScore: 94,
      qualityStatus: 'EXCELLENT',
      retentionCurve: [
        { timestampSec: 2.5, retentionRisk: 'LOW', dropOffReason: 'High tension question hook in first 1.2s prevents scroll drop-off.' },
        { timestampSec: 8.0, retentionRisk: 'LOW', dropOffReason: 'Kinetic zoom punch-in and bold word highlight hold steady attention.' },
        { timestampSec: 14.0, retentionRisk: 'LOW', dropOffReason: 'Clear payoff resolution and call-to-action.' }
      ],
      critiquePoints: [
        'Exceptional opening 1.5s hook delivery with zero dead space.',
        'High-energy bold word emphasis on "BIGGEST MISTAKE" and "ISOLATION".'
      ],
      reEditRecommendations: [
        'Maintained BOLD_CREATOR kinetic caption styling.',
        'Applied 1.15x face center zoom on punchline.'
      ],
      iterationCount: 2,
      evaluatedAt: new Date().toISOString()
    },
    iterationHistory: [
      { version: 1, score: 72, changesSummary: 'v1 Initial Cut: Detected 0.9s initial silence and static camera angle.', timestamp: new Date(Date.now() - 3600000).toISOString() },
      { version: 2, score: 94, changesSummary: 'v2 AI Polish: Trimmed 0.9s dead space, injected 1.15x punch-in at 3.7s, and highlighted keyword captions.', timestamp: new Date().toISOString() }
    ],
    status: 'ready',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    tags: ['Startups', 'Founder Advice', 'SaaS Growth'],
    scoreBreakdown: {
      overallScore: 94,
      sourcePotentialScore: 84,
      editQualityScore: 94,
      postRenderQualityScore: 94,
      hookStrength: 98,
      emotionalEnergy: 91,
      clarityScore: 95,
      standaloneContext: 92,
      pacingScore: 94,
      visualInterest: 89,
      explanationText:
        'Instant curiosity tension in first 2 seconds, punchy rhythm with zero filler words, and strong actionable contrast.',
    },
    captions: {
      id: 'cap-101',
      clipId: 'clip-101',
      language: 'en',
      preset: 'BOLD_CREATOR',
      fontFamily: 'Inter',
      fontSize: 48,
      textColor: '#FFFFFF',
      highlightColor: '#22D3EE',
      strokeColor: '#000000',
      strokeWidth: 4,
      backgroundColor: 'transparent',
      positionY: 74,
      wordAnimation: true,
      autoEmojis: true,
      segments: [
        {
          id: 'cseg-1',
          startSec: 0.0,
          endSec: 4.8,
          text: 'The biggest mistake early founders make is building for months in isolation without talking to paying customers.',
          words: [
            { word: 'The', startSec: 0.0, endSec: 0.3 },
            { word: 'BIGGEST', startSec: 0.3, endSec: 0.7, highlight: true },
            { word: 'MISTAKE', startSec: 0.7, endSec: 1.1, highlight: true },
            { word: 'early', startSec: 1.1, endSec: 1.4 },
            { word: 'founders', startSec: 1.4, endSec: 1.9 },
            { word: 'make', startSec: 1.9, endSec: 2.2 },
            { word: 'is', startSec: 2.2, endSec: 2.4 },
            { word: 'building', startSec: 2.4, endSec: 2.9 },
            { word: 'for', startSec: 2.9, endSec: 3.1 },
            { word: 'months', startSec: 3.1, endSec: 3.5 },
            { word: 'in', startSec: 3.5, endSec: 3.7 },
            { word: 'ISOLATION', startSec: 3.7, endSec: 4.3, highlight: true },
            { word: 'without', startSec: 4.3, endSec: 4.5 },
            { word: 'customers.', startSec: 4.5, endSec: 4.8 },
          ],
        },
        {
          id: 'cseg-2',
          startSec: 4.9,
          endSec: 9.8,
          text: 'When we started, we thought our proprietary algorithm was the only differentiator.',
          words: [
            { word: 'When', startSec: 4.9, endSec: 5.2 },
            { word: 'we', startSec: 5.2, endSec: 5.4 },
            { word: 'started,', startSec: 5.4, endSec: 5.8 },
            { word: 'we', startSec: 5.8, endSec: 6.0 },
            { word: 'thought', startSec: 6.0, endSec: 6.4 },
            { word: 'our', startSec: 6.4, endSec: 6.6 },
            { word: 'proprietary', startSec: 6.6, endSec: 7.2 },
            { word: 'ALGORITHM', startSec: 7.2, endSec: 7.8, highlight: true },
            { word: 'was', startSec: 7.8, endSec: 8.0 },
            { word: 'the', startSec: 8.0, endSec: 8.2 },
            { word: 'only', startSec: 8.2, endSec: 8.5 },
            { word: 'differentiator.', startSec: 8.5, endSec: 9.8 },
          ],
        },
        {
          id: 'cseg-3',
          startSec: 9.9,
          endSec: 16.5,
          text: 'Within 3 weeks, we realized nobody cared about technical complexity—they just wanted 4 hours reduced to 4 clicks.',
          words: [
            { word: 'Within', startSec: 9.9, endSec: 10.2 },
            { word: '3', startSec: 10.2, endSec: 10.5, highlight: true },
            { word: 'weeks,', startSec: 10.5, endSec: 11.0 },
            { word: 'nobody', startSec: 11.0, endSec: 11.4 },
            { word: 'cared', startSec: 11.4, endSec: 11.8 },
            { word: 'about', startSec: 11.8, endSec: 12.1 },
            { word: 'complexity.', startSec: 12.1, endSec: 12.9 },
            { word: 'They', startSec: 12.9, endSec: 13.2 },
            { word: 'wanted', startSec: 13.2, endSec: 13.6 },
            { word: 'FOUR', startSec: 13.6, endSec: 14.1, highlight: true },
            { word: 'HOURS', startSec: 14.1, endSec: 14.7, highlight: true },
            { word: 'to', startSec: 14.7, endSec: 15.0 },
            { word: 'FOUR', startSec: 15.0, endSec: 15.5, highlight: true },
            { word: 'CLICKS! 🚀', startSec: 15.5, endSec: 16.5, highlight: true },
          ],
        },
      ],
    },
    cropSettings: {
      x: 0.5,
      y: 0.45,
      scale: 1.15,
      smartTrack: true,
      backgroundMode: 'blur',
      backgroundColor: '#09090B',
    },
    overlays: {
      headlineText: '🛑 STOP MAKING THIS FOUNDER ERROR',
      headlineColor: '#FFFFFF',
      headlineBg: '#8B5CF6',
      showProgressBar: true,
      progressBarColor: '#22D3EE',
      ctaText: 'Follow @clipforge for daily startup secrets',
      ctaPosition: 'bottom',
    },
    views: 142800,
    engagementRate: 8.9,
    shares: 4120,
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'clip-102',
    projectId: 'proj-1',
    title: 'Why Customers Never Care About Your Code',
    hookStatement: 'Nobody cares about your complex tech stack until it solves their immediate pain.',
    startSec: 18.0,
    endSec: 42.0,
    durationSec: 24.0,
    aspectRatio: '9:16',
    highlightScore: 89,
    status: 'ready',
    thumbnailUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&auto=format&fit=crop&q=80',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    tags: ['Tech Strategy', 'Product Design'],
    scoreBreakdown: {
      overallScore: 89,
      hookStrength: 88,
      emotionalEnergy: 86,
      clarityScore: 92,
      standaloneContext: 90,
      pacingScore: 87,
      visualInterest: 85,
      explanationText:
        'High relatable tension for developers, with strong problem-solution cadence.',
    },
    captions: {
      id: 'cap-102',
      clipId: 'clip-102',
      language: 'en',
      preset: 'KARAOKE_GLOW',
      fontFamily: 'Inter',
      fontSize: 46,
      textColor: '#FFFFFF',
      highlightColor: '#8B5CF6',
      strokeColor: '#000000',
      strokeWidth: 4,
      backgroundColor: 'rgba(0,0,0,0.4)',
      positionY: 76,
      wordAnimation: true,
      autoEmojis: true,
      segments: [
        {
          id: 'cseg-201',
          startSec: 18.0,
          endSec: 23.5,
          text: 'You can spend six months polishing your backend architecture, but if user onboarding takes more than 30 seconds, they will leave.',
          words: [
            { word: 'You', startSec: 18.0, endSec: 18.3 },
            { word: 'can', startSec: 18.3, endSec: 18.5 },
            { word: 'spend', startSec: 18.5, endSec: 18.8 },
            { word: 'SIX', startSec: 18.8, endSec: 19.3, highlight: true },
            { word: 'MONTHS', startSec: 19.3, endSec: 19.8, highlight: true },
            { word: 'on', startSec: 19.8, endSec: 20.0 },
            { word: 'architecture...', startSec: 20.0, endSec: 21.0 },
            { word: 'they', startSec: 21.0, endSec: 21.4 },
            { word: 'will', startSec: 21.4, endSec: 21.8 },
            { word: 'LEAVE.', startSec: 21.8, endSec: 23.5, highlight: true },
          ],
        },
      ],
    },
    cropSettings: {
      x: 0.5,
      y: 0.42,
      scale: 1.2,
      smartTrack: true,
      backgroundMode: 'blur',
      backgroundColor: '#09090B',
    },
    overlays: {
      headlineText: '⚡ THE BRUTAL PRODUCT TRUTH',
      headlineColor: '#FFFFFF',
      headlineBg: '#EF4444',
      showProgressBar: true,
      progressBarColor: '#8B5CF6',
      ctaText: 'Share this with a developer friend',
    },
    views: 89400,
    engagementRate: 7.4,
    shares: 1940,
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'clip-103',
    projectId: 'proj-1',
    title: 'How To Validate Any SaaS Idea in 21 Days',
    hookStatement: 'If you cannot find 5 people willing to pay in 3 weeks, stop building immediately.',
    startSec: 45.0,
    endSec: 72.0,
    durationSec: 27.0,
    aspectRatio: '9:16',
    highlightScore: 86,
    status: 'ready',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    previewVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    tags: ['Validation', 'Customer Discovery'],
    scoreBreakdown: {
      overallScore: 86,
      hookStrength: 87,
      emotionalEnergy: 82,
      clarityScore: 89,
      standaloneContext: 84,
      pacingScore: 86,
      visualInterest: 80,
      explanationText:
        'Structured 3-step actionable guide that keeps viewers hooked through the final tip.',
    },
    captions: {
      id: 'cap-103',
      clipId: 'clip-103',
      language: 'en',
      preset: 'MINIMAL',
      fontFamily: 'Inter',
      fontSize: 44,
      textColor: '#FFFFFF',
      highlightColor: '#10B981',
      strokeColor: '#000000',
      strokeWidth: 3,
      backgroundColor: 'transparent',
      positionY: 72,
      wordAnimation: true,
      autoEmojis: true,
      segments: [],
    },
    cropSettings: {
      x: 0.5,
      y: 0.45,
      scale: 1.1,
      smartTrack: true,
      backgroundMode: 'blur',
      backgroundColor: '#09090B',
    },
    overlays: {
      headlineText: '💡 21-DAY SAAS VALIDATION FRAMEWORK',
      headlineColor: '#FFFFFF',
      headlineBg: '#10B981',
      showProgressBar: true,
      progressBarColor: '#10B981',
      ctaText: 'Save this post for your next project',
    },
    views: 65100,
    engagementRate: 9.1,
    shares: 2800,
    createdAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
];

export const INITIAL_PROJECTS: Project[] = [];

export const INITIAL_LIVE_SESSION: LiveSession = {
  id: 'live-sess-1',
  workspaceId: 'ws-forge-1',
  title: 'Weekly Tech Roundtable & Creator AMA Broadcast',
  rtmpSourceUrl: 'rtmp://ingest.clipforge.ai/live/nexus-stream-441',
  status: 'live',
  ingestBitrate: 6840,
  latencyMs: 120,
  durationSec: 4120,
  fps: 60,
  minScoreThreshold: 80,
  autoExport: true,
  moments: [
    {
      id: 'lm-1',
      timestamp: '01:04:12',
      durationSec: 24,
      title: 'Breaking: Why OpenAI announced real-time video streaming APIs',
      score: 96,
      status: 'approved',
      previewUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&auto=format&fit=crop&q=80',
      snippet: 'This changes the entire video pipeline forever. The latency went from 30s to 400ms.',
    },
    {
      id: 'lm-2',
      timestamp: '00:48:30',
      durationSec: 18,
      title: 'Audience Question: How to get first 10,000 TikTok followers?',
      score: 88,
      status: 'pending',
      previewUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&auto=format&fit=crop&q=80',
      snippet: 'Hook them in the first 0.8 seconds. Show the payoff before explaining the setup.',
    },
    {
      id: 'lm-3',
      timestamp: '00:22:15',
      durationSec: 32,
      title: 'Live Demo Fail Turned Into Hilarious Viral Moment',
      score: 92,
      status: 'exported',
      previewUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
      snippet: 'When your demo breaks on live stream with 5,000 people watching, just laugh!',
    },
  ],
};
